version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: npm-global-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Package install
          command: npm ci --prefer-offline
      - save_cache:
          key: npm-global-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm

      - run:
          name: Lint
          command: npm run lint
